spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=lmd_recpay_svc
      username: postgres
      password: lifemiles.2020
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
               lob:
                  non_contextual_creation: true
            default_schema: lmd_recpay_svc
app-properties:
   client-repository: ClientRepository